Rewrite request, add test for http server
GrayHatter/verse pull request #35
Opened 2024-12-20 19:04 UTC by GrayHatter

2024-12-20 19:07 UTC, GrayHatter commented
I plan to rebase this on top of the iovec commits

2024-12-21 01:53 UTC, e0ff requested changes

2024-12-21 01:53 UTC, e0ff commented on src/zwsgi.zig
> +        const buf: []u8 = try a.alloc(u8, uwsgi_header.size);
Shouldn't there be a defer for freeing this?

2024-12-21 01:53 UTC, e0ff commented on src/zwsgi.zig
> +            .vars = vars,
We need a deinit method for zWSGIRequest to free vars.

2024-12-21 02:10 UTC, e0ff approved these changes

2024-12-21 02:15 UTC, closed without merging